import type { Metadata } from "next";
import "../public/globals.css";
import { GlobalStyle } from "./styles/global";
import Navbar from "./component/navbar/Navbar";
import { AuthProvider } from "@/auth-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
